services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rwhdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/rwhdb
    depends_on:
      - db
volumes:
  dbdata:
